### ISSUE TITLE
[Discussion] Adding two extra custom fields

### ISSUE THREAD

**Issue by orschiro** [coughski/timer#2]
Hi @coughski, 

Thanks for updating the package in the webstore to release the "show remaining minutes" feature. 

I would like to discuss the following point with you:

What do you think of adding two extra custom fields? 

At least for me, I would like to have two more. :) 

Warmly,

Robert

**Comment by coughski** [comment]
@orschiro , thanks for contributing! If you submit a pull request for the 2 additional fields, I can add it.

**Comment by orschiro** [comment]
@coughski 

I will see what I can do!

Warmly,

Robert

**Comment by salva-dev** [comment]
It's also a interesting feature for me.

**Comment by orschiro** [comment]
Dear @santagu,

Apologies but I won't provide any pull request as I am no longer using the extension.

Warmly,

~Robert
